services:
  db:
    image: postgres:16-alpine
    container_name: todo-db
    restart: unless-stopped

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    volumes:
      - todo-postgres-data:/var/lib/postgresql/data

    networks:
      - todo-network

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    image: krishmini/todo-api:1.0.0
    container_name: todo-api
    restart: unless-stopped

    ports:
      - "${PORT}:3000"

    environment:
      PORT: 3000
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

    depends_on:
      db:
        condition: service_healthy

    networks:
      - todo-network

  stats-api:
    image: krishmini/stats-api:1.0.0
    container_name: stats-api
    restart: unless-stopped

    ports:
      - "8000:8000"

    environment:
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}

    depends_on:
      db:
        condition: service_healthy

    networks:
      - todo-network

volumes:
  todo-postgres-data:
    name: todo-postgres-data

networks:
  todo-network:
    name: todo-network
    driver: bridge